---

- name: "Inkscape PPA"
  apt_repository:
    repo: "{{ inkscape_ppa }}"
    update_cache: yes
    state: present
  become: yes

- name: "Inkscape install"
  apt:
    name: inkscape
    state: latest
  become: yes
