---
# SpiderOak - https://spideroak.com/opendownload

- name: "Check if SpiderOak is installed"
  command: "dpkg-query -W spideroakone"
  register: spideroak_installed
  failed_when: spideroak_installed.rc > 1
  changed_when: spideroak_installed.rc == 1

- name: "SpiderOak install"
  apt:
    deb: "{{ spideroak_download_url }}"
  sudo: true
  when: spideroak_installed.rc == 1

- name: "SpiderOak GPG key"
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: "{{ spideroak_gpg_key }}"
    state: present
  sudo: true
