---

- name: "Tilix PPA"
  apt_repository:
    repo: "{{ tilix_ppa }}"
    update_cache: yes
    state: present
  become: yes

- name: "Tilix install"
  apt:
    name: tilix
    state: latest
  become: yes
