---
# Glide

- name: "Glide PPA"
  sudo: yes
  apt_repository:
    repo: "{{ glide_ppa }}"
    update_cache: yes
    state: present

- name: "Glide install"
  sudo: yes
  apt:
    name: glide
    state: present
