---
# Glide

- name: "Glide PPA"
  apt_repository:
    repo: "{{ glide_ppa }}"
    update_cache: yes
    state: present
  become: yes

- name: "Glide install"
  apt:
    name: glide
    state: latest
  become: yes
