---

# Virtual Box - https://www.virtualbox.org/wiki/Linux_Downloads

- name: "Virtual Box GPG key"
  apt_key:
    url: "{{ virtualbox_gpg_url }}"
    state: present
  sudo: yes

- name: "Virtual Box repository"
  apt_repository:
    repo: "{{ virtualbox_repo }}"
    state: present
    filename: 'virtualbox'
  sudo: yes

- name: "Virtual Box install"
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: latest
  sudo: yes
