---

- name: "Screen install"
  apt:
    name: screen
    state: latest
  become: yes

- name: "Create screenrc file"
  copy:
    src: ./files/.screenrc
    dest: "{{ screenrc_dest_path }}"
    backup: yes
