---

- name: "Silent Cast PPA"
  apt_repository:
    repo: "{{ silentcast_ppa }}"
    update_cache: yes
    state: present
  become: yes

- name: "Silent Cast install"
  apt:
    name: silentcast
    state: latest
  become: yes
