---

- name: "Silent Cast PPA"
  apt_repository:
    repo: "{{ silentcast_ppa }}"
    update_cache: yes
    state: present
  sudo: yes

- name: "Silent Cast install"
  apt:
    name: silentcast
    state: latest
  sudo: yes
