---

- name: "Silent Cast PPA"
  sudo: yes
  apt_repository:
    repo: "{{ silentcast_ppa }}"
    update_cache: yes
    state: present

- name: "Silent Cast install"
  sudo: yes
  apt:
    name: silentcast
    state: present
