---
# Gogland - https://download.jetbrains.com/go/gogland-171.3780.106.tar.gz

- name: "Check Gogland existence"
  stat:
    path: "{{ gogland_dest }}Gogland-{{ gogland_version }}/bin/gogland.sh"
  register: goglang_stat

- name : "Gogland install"
  unarchive:
    src: "{{ gogland_download_url }}"
    remote_src: yes
    dest: "{{ gogland_dest }}"
  become: yes
  when: goglang_stat.stat.exists == False

- name: "Remove previous Gogland symlink"
  file:
   path: "{{ gogland_symlink }}"
   state: absent
  become: yes
  when: goglang_stat.stat.exists == False

- name: "Create Gogland symlink"
  file:
    src: "{{ gogland_dest }}Gogland-{{ gogland_version }}"
    dest: "{{ gogland_symlink }}"
    state: link
  become: yes
  when: goglang_stat.stat.exists == False
