---
# Calibre - https://calibre-ebook.com/download_linux

- name: Check Calibre existence
  command: "calibre --version"
  register: calibre_installed
  failed_when: calibre_installed.rc > 2
  changed_when: (calibre_installed.rc == 2 or calibre_installed.rc == 1) and calibre_force == false

- name: Calibre install
  shell: "{{ calibre_cmd }}"
  when: calibre_installed.rc == 2 or calibre_installed.rc == 1 or calibre_force == true
  become: yes
