---

- name: "Ubuntu Make PPA"
  apt_repository:
    repo: "{{ ubuntu_make_ppa }}"
    update_cache: yes
    state: present
  sudo: yes

- name: "Ubuntu Make install"
  apt:
    name: ubuntu-make
    state: latest
  sudo: yes
