---
- name: "Java webupd8team PPA"
  apt_repository:
    repo: "{{ java_ppa }}"
    update_cache: yes
    state: present
  become: yes

- name: "Java accept license"
  shell: "echo {{ java_name }} shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections"
  become: yes
  when java_accept_license == true

- name: "Java install"
  apt:
    name: "{{ java_name }}"
    state: latest
  become: yes
