---

- name: "Ansible PPA"
  apt_repository:
    repo: "{{ ansible_ppa }}"
    update_cache: yes
    state: present
  sudo: yes

- name: "Ansible install"
  apt:
    name:
      - software-properties-common
      - ansible
    state: latest
  sudo: yes
