---
# Slack - https://slack.com/downloads/linux
- name: "Check if Slack is installed"
  command: "dpkg-query -W -f='${Version}' slack-desktop"
  register: slack_installed_version
  failed_when: slack_installed_version.rc > 1
  changed_when: slack_installed_version.rc == 1

- name: "Slack install"
  apt:
    deb: "{{ slack_download_url }}"
  become: true
  when: slack_installed_version.rc == 1 or slack_installed_version.stdout != slack_version
