---
# Slack - https://slack.com/downloads/linux

- name: "Check if Slack is installed"
  command: "dpkg-query -W slack-desktop"
  register: slack_installed
  failed_when: slack_installed.rc > 1
  changed_when: slack_installed.rc == 1

- name: "Slack install"
  apt:
    deb: "{{ slack_download_url }}"
  sudo: true
  when: slack_installed.rc == 1
