---

# Yarn - https://yarnpkg.com/en/docs/install

- name: "Yarn GPG key"
  apt_key:
    url: "{{ yarn_gpg_url }}"
    state: present
  become: yes

- name: "Yarn repository"
  apt_repository:
    repo: "{{ yarn_repo }}"
    state: present
    filename: 'yarn'
  become: yes

- name: "Yarn install"
  apt:
    name: yarn
    state: latest
  become: yes
