---

# Atom - https://github.com/atom/atom/releases

- name: "Check if Atom is installed"
  command: "dpkg-query -W atom"
  register: atom_installed
  failed_when: atom_installed.rc > 1
  changed_when: atom_installed.rc == 1

- name: "Atom install"
  apt:
    deb: "{{ atom_download_url }}"
  become: true
  when: atom_installed.rc == 1 or atom_force == true
