---
# Git

- name: "Git PPA"
  apt_repository:
    repo: "{{ git_ppa }}"
    update_cache: yes
    state: present
  become: yes

- name: "Git install"
  apt:
    name: git
    state: latest
  become: yes

# Git config

- name: "Create gitconfig file"
  template:
    src: template/gitconfig.j2
    dest: "/home/{{ ansible_env.USER }}/.gitconfig"
    backup: yes

#- name: "Create gitconfig file"
#  copy:
#    src: ./files/.gitconfig
#    dest: "/home/{{ ansible_env.USER }}/.gitconfig"
#    force: no
