---

- name: "Homebank PPA"
  apt_repository:
    repo: "{{ homebank_ppa }}"
    update_cache: yes
    state: present
  sudo: yes

- name: "Homebank install"
  apt:
    name: homebank
    state: latest
  sudo: yes
