---

- name: "OBS Studio PPA"
  apt_repository:
    repo: "{{ obs_studio_ppa }}"
    update_cache: yes
    state: present
  sudo: yes

- name: "OBS Studio install"
  apt:
    name: obs-studio
    state: latest
  sudo: yes
