---
# OcenAudio - https://www.ocenaudio.com/download

- name: "Check if OcenAudio is installed"
  command: "dpkg-query -W ocenaudio"
  register: ocenaudio_installed
  failed_when: ocenaudio_installed.rc > 1
  changed_when: ocenaudio_installed.rc == 1

- name: "OcenAudio download"
  get_url:
    url: "{{ ocenaudio_download_url }}"
    dest: "{{ ocenaudio_temp_debdir }}/ocenaudio_debian64.deb"
  when: ocenaudio_installed.rc == 1

- name: "OcenAudio install"
  apt:
    deb: "{{ ocenaudio_temp_debdir }}/ocenaudio_debian64.deb"
  sudo: true
  when: ocenaudio_installed.rc == 1
