---

# Powerline Shell - https://github.com/banga/powerline-shell

- name: Check if Powerline Shell is already installed
  stat:
    path: "{{ powerline_shell_symlink }}"
  register: powerline_shell_installed

- name: Creates Global Powerline directory
  file:
    path: "{{ powerline_shell_global_dest_path }}"
    state: directory
  when: powerline_shell_installed.stat.exists == false or powerline_shell_force == true

- name: Clone powerline-shell GitHub repository
  git:
    repo: "{{ powerline_shell_git_repository }}"
    dest: "{{ powerline_shell_dest_path }}"
    accept_hostkey: yes
  when: powerline_shell_installed.stat.exists == false or powerline_shell_force == true

- name: Create powerline-shell configuration
  copy:
    remote_src: yes
    src: "{{ powerline_shell_dest_path }}config.py.dist"
    dest: "{{ powerline_shell_dest_path }}config.py"
  when: powerline_shell_installed.stat.exists == false or powerline_shell_force == true

- name: Generate powerline-shell file
  command: ./install.py
  args:
    chdir: "{{ powerline_shell_dest_path }}"
  when: powerline_shell_installed.stat.exists == false or powerline_shell_force == true

- name: Create powerline-shell symlink
  file:
    src: "{{ powerline_shell_dest_path }}powerline-shell.py"
    dest: "{{ powerline_shell_symlink }}"
    state: link
  when: powerline_shell_installed.stat.exists == false or powerline_shell_force == true
