---
# Packer - https://www.packer.io/downloads.html

- name: Check Packer version
  command: "packer --version"
  register: packer_installed_version
  failed_when: packer_installed_version.rc > 2
  changed_when: packer_installed_version.rc == 2 or packer_installed_version.rc == 1

- name: Install Packer
  unarchive:
    src: "{{ packer_download_url }}"
    dest: "{{ packer_dest }}"
    remote_src: yes
  become: yes
  when: packer_installed_version.rc == 2 or packer_installed_version.rc == 1 or packer_installed_version.stdout != packer_version
