---
# GVM - https://github.com/moovweb/gvm
- name: Install dependencies
  package:
    pkg: "{{ item }}"
    state: present
  with_items:
    - git

- name: Check GVM install
  stat:
    path: "{{ gvm_path }}"
  register: gvm_installed

- name: Install GVM
  shell: bash < <(curl -s -S -L {{ gvm_installer_url }})
  args:
    executable: /bin/bash
  register: gvm_result
  when: gvm_installed.stat.exists == false

- name: Check Golang target version
  shell: "source '{{ gvm_path }}' && gvm use go{{ golang_version }}"
  args:
    executable: /bin/bash
  register: gvm_installed_version
  failed_when: gvm_installed_version.rc > 1
  changed_when: gvm_installed_version.rc == 1

- name: Install Golang target version
  shell: "source '{{ gvm_path }}' && gvm install go{{ golang_version }} {{golang_install_option}}"
  args:
    executable: /bin/bash
  when: gvm_installed_version.rc == 1

- name: Activate Golang target version
  shell: "source '{{ gvm_path }}' && gvm use go{{ golang_version }} --default"
  args:
    executable: /bin/bash
  when: gvm_installed_version.rc == 1
